version: 0.2.0.{build}
environment:
  stage: alpha
  release_notes: 'Add FogParam, RotationValueOpenGL, BindBufferTarget, GenDeleteBuffer analyzers.'
  solution_path: src\OpenTKAnalyzer.sln
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
  - /feature\/.+/
  - /release\/.+/
  - /hotfix\/.+/
  - /support\/.+/
os: Visual Studio 2015
configuration: AppVeyor_NuGet
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    $VERSION = $env:APPVEYOR_BUILD_VERSION

    $STAGE = $env:stage


    $vs = $VERSION -split "\."

    $env:nupkg_version = $vs[0] + "." + $vs[1] + "." + $vs[2]

    $env:is_prerelease = "false"

    if($STAGE -ne "release"){ # prerelease
        $env:nupkg_version = $env:nupkg_version + "-" + $STAGE

        $env:is_prerelease = "true"
    }


    # rewrite

    $nuspec = (ls $env:APPVEYOR_BUILD_FOLDER -Recurse).Where{ $_.Extension -eq ".nuspec"} | Select -First 1

    [xml]$xml = Get-Content $nuspec.FullName

    $xml.package.metadata.version = $env:nupkg_version

    $xml.package.metadata.releaseNotes = $env:release_notes

    $xml.Save($nuspec.FullName)


    nuget restore $env:solution_path



    Remove-Item "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Amazon Web Services LLC" -Recurse -Force
build:
  project: $(solution_path)
  verbosity: minimal
after_build:
- ps: >-
    $folder = $env:APPVEYOR_BUILD_FOLDER + "\" + ($env:solution_path -split "\.")[0]

    (Get-ChildItem $folder -Recurse).Where{ $_.Extension -eq ".nupkg"} | %{ Push-AppveyorArtifact $_.FullName -FileName $_.Name }
deploy:
- provider: NuGet
  api_key:
    secure: e6vaTPs/qG5DkeYt4zWnEwOEzMTRa+Fskx7k5GAz8OYGafTzasM5FX54JhiiJjFR
  on:
    branch: master
- provider: GitHub
  tag: $(nupkg_version)
  release: $(nupkg_version)
  description: $(release_notes)
  auth_token:
    secure: ld1RBkNTi/7LQRJhZJXjATWL/TdysxJRPcTjyKVvsnLumE7ulNyIUy40eASxX4bv
  prerelease: $(is_prerelease)
  on:
    branch: master