using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using OpenTK.Graphics.OpenGL;
using OpenTKAnalyzer.Utility;

namespace OpenTKAnalyzer.OpenTK_.Graphics_.OpenGL_
{
	[DiagnosticAnalyzer(LanguageNames.CSharp)]
	public class GenDeleteBufferAnalyzer : DiagnosticAnalyzer
	{
		public const string DiagnosticId = "GenerateDeleteBuffer";

		private const string Title = "GL.GenBuffer and GL.DeleteBuffer usage";
		private const string NoConstantMessageFormat = "{0} accepts variable.";
		private const string NotUsedMessageFormat = "Generated by this " + nameof(GL) + "." + nameof(GL.GenBuffer) + " is not used.";
		private const string BuffersNumberMessageFormat = "{0} accepts larger than 0 value on 1st argument.";
		private const string DuplexGenBuffersMessageFormat = "The variable \"{0}\" is used in multiple " + nameof(GL) + "." + nameof(GL.GenBuffers) + ".";
		private const string DuplexDeleteBuffersMessageFormat = "The variable \"{0}\" is used in multiple " + nameof(GL) + "." + nameof(GL.DeleteBuffers) + ".";
		private const string LackGenBuffersMessageFormat = "The variable \"{0}\" is used deleting but not generating.";
		private const string LackDeleteBuffersMessageFormat = "The variable \"{0}\" is used generating but not deleting.";
		private const string GenDeleteNumberOfBuffersMessageFormat = nameof(GL) + "." + nameof(GL.GenBuffers) + " and " + nameof(GL) + "." + nameof(GL.DeleteBuffers) + " of the variable \"{0}\" may have different number of buffer.";
		private const string Description = "Analyzer for GL.GenBuffer and GL.DeleteBuffer.";
		private const string Category = nameof(OpenTKAnalyzer) + ":" + nameof(OpenTK.Graphics.OpenGL);

		internal static DiagnosticDescriptor NoConstantRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: NoConstantMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor NotUsedRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: NotUsedMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor BuffersNumberRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: BuffersNumberMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor DuplexGenBuffersRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: DuplexGenBuffersMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor DuplexDeleteBuffersRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: DuplexDeleteBuffersMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor LackGenBuffersRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: DuplexDeleteBuffersMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor LackDeleteBuffersRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: DuplexDeleteBuffersMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor GenDeleteNumberOfBuffersRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: GenDeleteNumberOfBuffersMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);


		public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(NoConstantRule, NotUsedRule, BuffersNumberRule, DuplexGenBuffersRule, DuplexDeleteBuffersRule, LackGenBuffersRule, LackDeleteBuffersRule, GenDeleteNumberOfBuffersRule);

		public override void Initialize(AnalysisContext context)
		{
			context.RegisterSemanticModelAction(Analyze);
		}

		private static async void Analyze(SemanticModelAnalysisContext context)
		{
			var root = await context.SemanticModel.SyntaxTree.GetRootAsync();

			var invocations = root.DescendantNodes().OfType<InvocationExpressionSyntax>();

			var genBufferOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.GenBuffer));

			var notUsedGenBufferOps = genBufferOps.Where(g => !g.Parent.IsKind(SyntaxKind.SimpleAssignmentExpression) && !g.Parent.IsKind(SyntaxKind.EqualsValueClause));
			foreach (var genOp in notUsedGenBufferOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: NotUsedRule,
					location: genOp.GetLocation()));
			}

			var genBuffersOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.GenBuffers));
			var firstArgConstGenBuffersOps = SelectFirstArgConstInt(genBufferOps);
			var invalidFirstArgGenBuffersOps = firstArgConstGenBuffersOps.Where(g => g.Item2.Value < 1);
			foreach (var genOp in invalidFirstArgGenBuffersOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: BuffersNumberRule,
					location: genOp.Item1.GetLocation(),
					messageArgs: nameof(GL) + "." + nameof(GL.GenBuffers)));
			}

			var deleteBufferOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.DeleteBuffer));
			var invalidDeleteBufferOps = SelectFirstArgConstInt(deleteBufferOps).Where(o => o.Item2.HasValue);
			foreach (var deleteLiteral in invalidDeleteBufferOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: NoConstantRule,
					location: deleteLiteral.Item1.GetLocation(),
					messageArgs: nameof(GL) + "." + nameof(GL.DeleteBuffer)));
			}

			var deleteBuffersOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.DeleteBuffers));
			var firstArgConstDeleteBuffersOps = SelectFirstArgConstInt(deleteBuffersOps);
			var invalidFirstArgDeleteBuffersOps = firstArgConstDeleteBuffersOps.Where(d => d.Item2.Value < 1);
			foreach (var deleteOp in invalidFirstArgDeleteBuffersOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: BuffersNumberRule,
					location: deleteOp.Item1.GetLocation(),
					messageArgs: nameof(GL) + "." + nameof(GL.DeleteBuffers));
			}

			var genOpGroupsById = GroupByVariableName(firstArgConstGenBuffersOps, context.SemanticModel);

			var deleteOpGroupsById = GroupByVariableName(firstArgConstDeleteBuffersOps, context.SemanticModel);
			foreach (var group in deleteOpGroupsById.Where(g => g.Skip(2).Any())) // 2 or more deletes with same variable
			{
				foreach (var deleteOp in group)
				{
					context.ReportDiagnostic(Diagnostic.Create(
						descriptor: DuplexDeleteBuffersRule,
						location: deleteOp.Item1.Parent.Parent.Parent.GetLocation(),
						messageArgs: group.Key.Split('.').Last()));
				}
			}

			var allKeys = Enumerable.Union(genOpGroupsById.Select(g => g.Key), deleteOpGroupsById.Select(d => d.Key));
			foreach (var key in allKeys)
			{
				var genOps = genOpGroupsById.FirstOrDefault(g => g.Key == key);
				var deleteOps = deleteOpGroupsById.FirstOrDefault(d => d.Key == key);
				bool isGenOpValid = true;
				bool isDeleteOpValid = true;

				if (genOps == null)
				{
					foreach (var delete in deleteOps)
					{
						context.ReportDiagnostic(Diagnostic.Create(
							descriptor: LackGenBuffersRule,
							location: delete.Item1.Parent.Parent.Parent.GetLocation(),
							messageArgs: key.Split('.').Last()));
					}
					isGenOpValid = false;
				}
				if (deleteOps == null)
				{
					foreach (var gen in genOps)
					{
						context.ReportDiagnostic(Diagnostic.Create(
							descriptor: LackDeleteBuffersRule,
							location: gen.Item1.Parent.Parent.Parent.GetLocation(),
							messageArgs: key.Split('.').Last()));
					}
					isDeleteOpValid = false;
				}

				if (isGenOpValid && genOps.Skip(2).Any()) // 2 or more gens with same variable
				{
					foreach (var gen in genOps)
					{
						context.ReportDiagnostic(Diagnostic.Create(
							descriptor: DuplexGenBuffersRule,
							location: gen.Item1.Parent.Parent.Parent.GetLocation(),
							messageArgs: key.Split('.').Last()));
					}
					isGenOpValid = false;
				}
				if (isDeleteOpValid && deleteOps.Skip(2).Any()) // 2 or more deletes with same variable
				{
					foreach (var delete in deleteOps)
					{
						context.ReportDiagnostic(Diagnostic.Create(
							descriptor: DuplexDeleteBuffersRule,
							location: delete.Item1.Parent.Parent.Parent.GetLocation(),
							messageArgs: key.Split('.').Last()));
					}
					isDeleteOpValid = false;
				}

				if (isGenOpValid || isDeleteOpValid)
				{
					continue;
				}

				// gen and delete are 1 to 1, but constant might different
				var genOp = genOps.First();
				var deleteOp = deleteOps.First();
				if (genOp.Item2.HasValue && deleteOp.Item2.HasValue)
				{
					if (genOp.Item2.Value != deleteOp.Item2.Value)
					{
						context.ReportDiagnostic(Diagnostic.Create(
							descriptor: GenDeleteNumberOfBuffersRule,
							location: genOp.Item1.Parent.Parent.Parent.GetLocation(),
							messageArgs: key));
						context.ReportDiagnostic(Diagnostic.Create(
							descriptor: GenDeleteNumberOfBuffersRule,
							location: deleteOp.Item1.Parent.Parent.Parent.GetLocation(),
							messageArgs: key));
					}
				}
				else if (genOp.Item2.HasValue || deleteOp.Item2.HasValue) // XOR so one is constant and another is variable
				{
					context.ReportDiagnostic(Diagnostic.Create(
						descriptor: GenDeleteNumberOfBuffersRule,
						location: genOp.Item1.Parent.Parent.Parent.GetLocation(),
						messageArgs: key));
					context.ReportDiagnostic(Diagnostic.Create(
						descriptor: GenDeleteNumberOfBuffersRule,
						location: deleteOp.Item1.Parent.Parent.Parent.GetLocation(),
						messageArgs: key));
				}
			}
		}

		private static IEnumerable<Tuple<ExpressionSyntax, int?>> SelectFirstArgConstInt(IEnumerable<InvocationExpressionSyntax> invocations)
		{
			return invocations.Select(g => g.ArgumentList.Arguments.FirstOrDefault()?.Expression)
				.Select(e => Tuple.Create(e, NumericValueParser.ParseFromExpressionIntOrNull(e)))
				.Where(v => v.Item2.HasValue);
		}

		private static IEnumerable<IGrouping<string, Tuple<ExpressionSyntax, int?>>> GroupByVariableName(IEnumerable<Tuple<ExpressionSyntax, int?>> ops, SemanticModel semanticModel)
		{
			return ops.Select(o =>
			{
				var genSecondArg = (o.Item1.Parent.Parent as ArgumentListSyntax)?.Arguments.Skip(1).FirstOrDefault()?.Expression;
				var genId = Identifier.GetVariableString(genSecondArg, semanticModel);
				return new { Expr = o.Item1, Const = o.Item2, Id = genId };
			}).Where(o => string.IsNullOrEmpty(o.Id))
			.GroupBy(g => g.Id, e => Tuple.Create(e.Expr, e.Const));
		}
	}
}