using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using OpenTK.Graphics.OpenGL;

namespace OpenTKAnalyzer.OpenTK_.Graphics_.OpenGL_
{
	[DiagnosticAnalyzer(LanguageNames.CSharp)]
	public class GenDeleteBufferAnalyzer : DiagnosticAnalyzer
	{
		public const string DiagnosticId = "GenerateDeleteBuffer";

		private const string Title = "GL.GenBuffer and GL.DeleteBuffer usage";
		private const string NoConstantMessageFormat = "{0} accepts variable.";
		private const string NotUsedMessageFormat = "Generated by this " + nameof(GL) + "." + nameof(GL.GenBuffer) + " is not used.";
		private const string GenBuffersNumberMessageFormat = nameof(GL) + "." + nameof(GL.GenBuffers) + " accepts larger than 0 value on 1st argument.";
		private const string Description = "Analyzer for GL.GenBuffer and GL.DeleteBuffer.";
		private const string Category = nameof(OpenTKAnalyzer) + ":" + nameof(OpenTK.Graphics.OpenGL);

		internal static DiagnosticDescriptor NoConstantRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: NoConstantMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor NotUsedRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: NotUsedMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Warning,
			isEnabledByDefault: true,
			description: Description);

		internal static DiagnosticDescriptor GenBuffersNumberRule = new DiagnosticDescriptor(
			id: DiagnosticId,
			title: Title,
			messageFormat: GenBuffersNumberMessageFormat,
			category: Category,
			defaultSeverity: DiagnosticSeverity.Error,
			isEnabledByDefault: true,
			description: Description);

		public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(NoConstantRule, NotUsedRule, GenBuffersNumberRule);

		public override void Initialize(AnalysisContext context)
		{
			context.RegisterSemanticModelAction(Analyze);
		}

		private static async void Analyze(SemanticModelAnalysisContext context)
		{
			var root = await context.SemanticModel.SyntaxTree.GetRootAsync();

			var invocations = root.DescendantNodes().OfType<InvocationExpressionSyntax>();

			var genBufferOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.GenBuffer));
			var genBuffersOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.GenBuffers));
			var deleteBufferOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.DeleteBuffer));
			var deleteBuffersOps = invocations.Where(i => i.Expression.WithoutTrivia().ToFullString() == nameof(GL) + "." + nameof(GL.DeleteBuffers));

			var notUsedGenBufferOps = genBufferOps.Where(g => !g.Parent.IsKind(SyntaxKind.SimpleAssignmentExpression) && !g.Parent.IsKind(SyntaxKind.EqualsValueClause));
			foreach (var genOp in notUsedGenBufferOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: NotUsedRule,
					location: genOp.GetLocation()));
			}

			var firstArgConstantGenBuffersOps = genBuffersOps.Select(g => g.ArgumentList.Arguments.FirstOrDefault()?.Expression)
				.OfType<LiteralExpressionSyntax>();
			var invalidFirstArgGenBuffersOps = firstArgConstantGenBuffersOps.Where(l => { double val; return double.TryParse(l.Token.ValueText, out val) && val < 1; });
			foreach (var genOp in invalidFirstArgGenBuffersOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: GenBuffersNumberRule,
					location: genOp.GetLocation()));
			}

			var invalidDeleteBufferOps = deleteBufferOps.Select(d => d.ArgumentList.Arguments.FirstOrDefault()?.Expression)
				.OfType<LiteralExpressionSyntax>();
			foreach (var deleteLiteral in invalidDeleteBufferOps)
			{
				context.ReportDiagnostic(Diagnostic.Create(
					descriptor: NoConstantRule,
					location: deleteLiteral.GetLocation(),
					messageArgs: nameof(GL) + "." + nameof(GL.DeleteBuffer)));
			}

			// TODO: GL.GenBuffers and GL.DeleteBuffers
		}
	}
}